include: package:flutter_lints/flutter.yaml
analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  exclude:
    - lib/generated/**
    - lib/generated_plugin_registrant.dart
linter:
  rules:
    always_declare_return_types: true
    prefer_single_quotes: true
    unawaited_futures: true
    package_api_docs: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    use_build_context_synchronously: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
